import { Agent, AgentCategory } from "@/lib/types";

export const categories: Array<"All" | AgentCategory> = [
  "All",
  "Travel",
  "Education",
  "Data",
  "Engineering",
  "Compute",
  "Research",
  "Business",
];

export const agents: Agent[] = [
  {
    id: "hotel-oracle",
    name: "Hotel Oracle",
    publisher: "Nomad Ops",
    tagline: "Finds refundable hotel options and drafts the booking plan.",
    description:
      "Compares hotel availability, cancellation policies, neighborhood safety, and loyalty perks before returning the best reservation choices.",
    category: "Travel",
    tags: ["hotel", "booking", "travel", "reservation", "refund"],
    hostingMode: "publisher-hosted",
    priceSats: 850,
    rating: 4.8,
    reviewCount: 184,
    successRate: 97,
    estimatedRuntime: "2 min",
    refundable: true,
    parameters: [
      { id: "city", label: "Destination city", type: "text", placeholder: "Paris, Tokyo, Lisbon", required: true },
      { id: "checkIn", label: "Check-in date", type: "date", placeholder: "YYYY-MM-DD", required: true },
      { id: "checkOut", label: "Check-out date", type: "date", placeholder: "YYYY-MM-DD", required: true },
      { id: "budget", label: "Nightly budget", type: "number", placeholder: "180", required: true },
      {
        id: "room",
        label: "Room preference",
        type: "select",
        placeholder: "Choose a room type",
        options: ["Solo", "Couple", "Family", "Business suite"],
      },
    ],
    sampleOutput: "Three refundable hotel options with booking links, total cost, and cancellation deadlines.",
    reviews: [
      { author: "Mia", rating: 5, comment: "Found a better flexible rate than I had on Booking." },
      { author: "Ken", rating: 4.7, comment: "Good neighborhood summary and fast recommendations." },
    ],
  },
  {
    id: "math-tutor-match",
    name: "Math Tutor Match",
    publisher: "TutorMesh",
    tagline: "Matches students with the right tutor and practice plan.",
    description:
      "Collects a student's goals, weaknesses, and schedule to recommend tutor profiles and a first-week learning plan.",
    category: "Education",
    tags: ["math", "tutor", "learning", "school", "homework"],
    hostingMode: "market-hosted",
    priceSats: 620,
    rating: 4.6,
    reviewCount: 91,
    successRate: 94,
    estimatedRuntime: "90 sec",
    refundable: true,
    parameters: [
      { id: "level", label: "Math level", type: "select", placeholder: "Choose level", options: ["Algebra", "Geometry", "Calculus", "Statistics"] },
      { id: "needs", label: "Student needs", type: "textarea", placeholder: "Exam prep, homework help, confidence, etc.", required: true },
      { id: "timezone", label: "Timezone", type: "text", placeholder: "UTC+2" },
    ],
    sampleOutput: "Tutor shortlist with strengths, hourly price, and a 7-day practice schedule.",
    reviews: [
      { author: "Lea", rating: 5, comment: "The tutor shortlist was precise and realistic." },
      { author: "Omar", rating: 4.5, comment: "The practice plan helped my daughter prepare." },
    ],
  },
  {
    id: "scrape-forge",
    name: "Scrape Forge",
    publisher: "Data Foundry",
    tagline: "Turns target websites into clean CSV, JSON, or Markdown datasets.",
    description:
      "Plans a compliant scraping run, extracts requested fields, deduplicates rows, and produces structured files ready for analysis.",
    category: "Data",
    tags: ["scraping", "data", "csv", "json", "website", "crawler"],
    hostingMode: "market-hosted",
    priceSats: 1400,
    rating: 4.9,
    reviewCount: 238,
    successRate: 96,
    estimatedRuntime: "6 min",
    refundable: true,
    parameters: [
      { id: "websites", label: "Target websites", type: "textarea", placeholder: "https://example.com/products\nhttps://example.org/catalog", required: true },
      { id: "fields", label: "Fields to extract", type: "textarea", placeholder: "title, price, email, location, description", required: true },
      { id: "format", label: "Output file type", type: "select", placeholder: "Choose format", options: ["CSV", "JSON", "Markdown", "Excel"] },
      { id: "depth", label: "Crawl depth", type: "number", placeholder: "2" },
    ],
    sampleOutput: "A cleaned dataset, source coverage report, and warnings for blocked or missing pages.",
    reviews: [
      { author: "Ari", rating: 5, comment: "Saved hours of manual copying for our lead list." },
      { author: "Nora", rating: 4.8, comment: "Clean JSON output and good blocked-page notes." },
    ],
  },
  {
    id: "code-sentinel",
    name: "Code Sentinel",
    publisher: "Review Labs",
    tagline: "Reviews pull requests for bugs, security risks, and missing tests.",
    description:
      "Inspects repository diffs, prioritizes concrete findings, and writes a review that focuses on regressions and production risk.",
    category: "Engineering",
    tags: ["code review", "security", "tests", "github", "pull request"],
    hostingMode: "publisher-hosted",
    priceSats: 1200,
    rating: 4.7,
    reviewCount: 311,
    successRate: 95,
    estimatedRuntime: "4 min",
    refundable: true,
    parameters: [
      { id: "repo", label: "Repository or PR URL", type: "url", placeholder: "https://github.com/org/repo/pull/42", required: true },
      { id: "focus", label: "Review focus", type: "select", placeholder: "Choose focus", options: ["Bugs", "Security", "Performance", "Tests", "All risks"] },
      { id: "context", label: "Extra context", type: "textarea", placeholder: "Anything the reviewer should know" },
    ],
    sampleOutput: "Prioritized findings with file references, risk level, and targeted test suggestions.",
    reviews: [
      { author: "Priya", rating: 4.8, comment: "Caught a race condition before deploy." },
      { author: "Sam", rating: 4.6, comment: "Good signal and very little noise." },
    ],
  },
  {
    id: "gpu-burst",
    name: "GPU Burst Planner",
    publisher: "Compute Guild",
    tagline: "Plans heavy compute jobs and estimates the cheapest GPU run.",
    description:
      "Chooses instance types, memory, batch size, and cost envelope for model training, rendering, or large simulations.",
    category: "Compute",
    tags: ["gpu", "compute", "training", "rendering", "simulation", "cost"],
    hostingMode: "market-hosted",
    priceSats: 2100,
    rating: 4.9,
    reviewCount: 77,
    successRate: 98,
    estimatedRuntime: "5 min",
    refundable: true,
    parameters: [
      { id: "workload", label: "Workload description", type: "textarea", placeholder: "Train a LoRA, render frames, run simulation...", required: true },
      { id: "deadline", label: "Deadline", type: "text", placeholder: "Tonight, 24 hours, next week" },
      { id: "budget", label: "Compute budget in USD", type: "number", placeholder: "80" },
    ],
    sampleOutput: "Recommended GPU, job plan, estimated cost, runtime, and fallback provider.",
    reviews: [
      { author: "Iris", rating: 5, comment: "Picked a cheaper A10G setup that still fit memory." },
      { author: "Theo", rating: 4.8, comment: "Great budget estimate for a short render job." },
    ],
  },
  {
    id: "research-radar",
    name: "Research Radar",
    publisher: "Signal Desk",
    tagline: "Finds source-backed answers and creates a research brief.",
    description:
      "Searches across public sources, ranks credibility, and turns findings into a concise brief with citations and open questions.",
    category: "Research",
    tags: ["research", "sources", "brief", "market", "analysis"],
    hostingMode: "publisher-hosted",
    priceSats: 980,
    rating: 4.5,
    reviewCount: 143,
    successRate: 92,
    estimatedRuntime: "3 min",
    refundable: true,
    parameters: [
      { id: "question", label: "Research question", type: "textarea", placeholder: "What should I know about...", required: true },
      { id: "depth", label: "Depth", type: "select", placeholder: "Choose depth", options: ["Quick brief", "Detailed memo", "Investor-grade scan"] },
      { id: "region", label: "Region or market", type: "text", placeholder: "EU, US, global" },
    ],
    sampleOutput: "Executive summary, source list, confidence notes, and next research questions.",
    reviews: [
      { author: "Rae", rating: 4.6, comment: "Useful brief with sources I had not found." },
      { author: "Julien", rating: 4.3, comment: "Fast overview, but I wanted more charts." },
    ],
  },
  {
    id: "growth-ops",
    name: "Growth Ops Agent",
    publisher: "Launch Stack",
    tagline: "Creates campaign workflows from a product goal.",
    description:
      "Turns acquisition goals into landing-page copy, email sequences, audience segments, and experiment checklists.",
    category: "Business",
    tags: ["growth", "marketing", "email", "sales", "automation"],
    hostingMode: "market-hosted",
    priceSats: 760,
    rating: 4.4,
    reviewCount: 69,
    successRate: 90,
    estimatedRuntime: "2 min",
    refundable: true,
    parameters: [
      { id: "product", label: "Product", type: "text", placeholder: "AI calendar assistant", required: true },
      { id: "audience", label: "Target audience", type: "text", placeholder: "Freelancers, founders, students", required: true },
      { id: "goal", label: "Growth goal", type: "select", placeholder: "Choose goal", options: ["Waitlist", "Paid users", "Retention", "Referrals"] },
    ],
    sampleOutput: "Campaign concept, 3 email drafts, landing-page headline set, and first experiments.",
    reviews: [
      { author: "Nico", rating: 4.4, comment: "Good first campaign for a weekend launch." },
      { author: "Tess", rating: 4.2, comment: "Useful email sequence and audience split." },
    ],
  },
  {
    id: "contract-reader",
    name: "Contract Reader",
    publisher: "Clause AI",
    tagline: "Summarizes risky clauses before you sign.",
    description:
      "Reviews pasted contract text, highlights unusual obligations, and suggests questions for a qualified lawyer.",
    category: "Business",
    tags: ["contract", "legal", "risk", "summary", "clauses"],
    hostingMode: "publisher-hosted",
    priceSats: 1100,
    rating: 4.6,
    reviewCount: 122,
    successRate: 93,
    estimatedRuntime: "3 min",
    refundable: true,
    parameters: [
      { id: "contract", label: "Contract text", type: "textarea", placeholder: "Paste the agreement text here", required: true },
      { id: "jurisdiction", label: "Jurisdiction", type: "text", placeholder: "France, Delaware, UK" },
      { id: "concern", label: "Main concern", type: "select", placeholder: "Choose concern", options: ["Payment terms", "IP ownership", "Termination", "Liability", "All clauses"] },
    ],
    sampleOutput: "Plain-language summary, risky clauses, negotiation questions, and lawyer follow-up notes.",
    reviews: [
      { author: "Ben", rating: 4.7, comment: "Highlighted an IP clause I nearly missed." },
      { author: "Sofia", rating: 4.5, comment: "Great first pass before legal review." },
    ],
  },
];
